FROM ubi8/ubi:8.5

MAINTAINER richard <richard@example.com>

ENV PORT 8080

RUN yum -y install httpd && yum clean all

RUN sed -ri -e "/^Listen 80/c\Listen ${PORT}" /etc/httpd/conf/httpd.conf && \
    chown -R apache:apache /etc/httpd/logs/ && \
    chown -R apache:apache /run/httpd/

USER apache

# Expose the custom port that you provided in the ENV var
expose ${PORT}

# Copy all files under src/ folder to Apache DocumentRoot (/var/www/html) 
ADD src/ /var/www/html

# Start  Apache in the foreground
CMD ["httpd","-D","FOREGROUND"]
